# Name of the workflow
name: Lint Code

# Trigger the workflow on every pull request
on:
  pull_request:
    branches:
      - main
# Define the jobs to be run
jobs:
  lint:
    # Use the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Define the steps for the job
    steps:
      # Step 1: Check out the code
      # This checks out the code from the pull request branch
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run ESLint
      # This runs ESLint using the rules defined in eslint.config.js
      - name: Run ESLint
        run: npx eslint .
